import MainNav from "@/components/main_nav/MainNav";
import "../globals.css";
import localFont from "next/font/local";

const myFont = localFont({
    src: "../../fonts/font.otf",
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={myFont.className}>
            <body>
                <MainNav />
                {children}
            </body>
        </html>
    );
}
